import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const sections=['INSTALL_RU.md','MEDIA.md','CONNECTORS.md'].map((file,index)=>`<section id="${['install','media','connectors'][index]}">${renderToStaticMarkup(React.createElement(Markdown,{remarkPlugins:[remarkGfm],skipHtml:true,components:{a:({href,children})=>React.createElement('a',{href:href?.endsWith('.md')?'https://github.com/darkdi/rant-agent/blob/main/docs/'+href:href},children)}},fs.readFileSync(path.join(root,'docs',file),'utf8')))}</section>`).join('');
fs.writeFileSync(path.join(root,'sever-ide/public/help.html'),`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Установка и помощь — Rant Agent</title><link rel="icon" href="/favicon.svg"><style>:root{color-scheme:light dark}body{font:16px/1.75 system-ui;max-width:960px;margin:40px auto;padding:0 24px;background:light-dark(#fafbfe,#17191d);color:light-dark(#172035,#f5f6fa)}a{color:light-dark(#0865f5,#6ea7ff)}h1,h2,h3{line-height:1.3;margin-top:2em}pre{padding:18px;overflow:auto;border:1px solid #8994a855;border-radius:12px;background:light-dark(#f0f3f9,#111318)}code{font-size:.9em}table{border-collapse:collapse;display:block;overflow:auto}td,th{padding:10px;border:1px solid #8994a855}nav{display:flex;gap:20px;flex-wrap:wrap}section{scroll-margin-top:20px}</style><nav><a href="/">← Rant Agent</a><a href="#install">Установка</a><a href="#media">Картинки и видео</a><a href="#connectors">Браузер и компьютер</a><a href="https://github.com/darkdi/rant-agent">GitHub</a></nav>${sections}</html>`);
console.log('Built offline installation and media guide.');
