'use client';
import { useEffect, useState } from 'react';
import { Check, ChevronRight, Sparkles, Search } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

type Model = {id:string;name:string;model:string;trial?:boolean;input_micro?:number;output_micro?:number};
type Balance = {name:string;plan:string;active:boolean;expires:number;remaining:number;credits:number;used:number;daily_remaining:number|null;daily_resets:number;pending:number;payments_enabled:boolean;plans:{id:string;name:string;price:number;credits:number}[]};
const number = (n:number) => n.toLocaleString('ru-RU',{maximumFractionDigits:2});
async function request<T>(path:string,body?:object):Promise<T>{
 const session=await fetch('/bridge/session').then(r=>r.json()) as {token:string};
 const r=await fetch('/bridge/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Sever-Token':session.token},...(body?{body:JSON.stringify(body)}:{})});
 const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error||'Не удалось получить данные');return data;
}
export function CloudModels({open,onClose,profiles,selected,onSelect,disabled}:{open:boolean;onClose:()=>void;profiles:Model[];selected:string;onSelect:(id:string)=>void;disabled:boolean}){
 const [search,setSearch]=useState('');
 return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="settings-dialog cloud-models"><DialogHeader><DialogTitle>Выбери помощника</DialogTitle><DialogDescription>Модели уже подключены. Переключай их в одном разговоре.</DialogDescription></DialogHeader><label className="cloud-search"><Search size={18}/><input aria-label="Найти модель" placeholder="GPT, Claude…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="cloud-model-grid">{profiles.filter(p=>(p.name+' '+p.model).toLowerCase().includes(search.toLowerCase())).map(p=><button key={p.id} disabled={disabled} className={selected===p.id?'selected':''} onClick={()=>{onSelect(p.id);onClose()}}><span className="cloud-model-icon">{p.model.startsWith('anthropic')?'C':'G'}</span><span><b>{p.name}</b><small>{p.trial?'Есть в пробном доступе':'Платные тарифы'} · {number((p.input_micro||0)/1000)} / {number((p.output_micro||0)/1000)} кр. за 1 000 токенов</small></span>{selected===p.id&&<Check size={18}/>}</button>)}</div><p className="cloud-fineprint">Первая цена — входящий контекст, вторая — ответ. Шаги агента и сжатие контекста тоже расходуют кредиты.</p></DialogContent></Dialog>;
}
export function CloudSubscription(){
 const [open,setOpen]=useState(false),[balance,setBalance]=useState<Balance|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[accept,setAccept]=useState(false);
 async function refresh(){try{setBalance(await request<Balance>('billing'));setError('')}catch(e){setError(String((e as Error).message))}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),30000);if(new URLSearchParams(location.search).has('payment'))setOpen(true);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(open)void refresh()},[open]);
 async function buy(plan:string){setBusy(true);setError('');try{const data=await request<{url:string}>('checkout',{plan,accept_terms:accept});location.assign(data.url)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><button className="cloud-balance-button" onClick={()=>setOpen(true)}><Sparkles size={17}/><span><b>{balance?.name||'Тариф и лимиты'}</b><small>{balance?`${number(balance.remaining)} из ${number(balance.credits)} кредитов`:'Пробный доступ на 7 дней'}</small></span><ChevronRight size={15}/></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="settings-dialog cloud-plans"><DialogHeader><DialogTitle>Твой запас возможностей</DialogTitle><DialogDescription>7 дней на знакомство без карты. Затем — доступ на 30 дней по выбранному тарифу.</DialogDescription></DialogHeader>{balance&&<div className="cloud-usage"><div><b>{balance.name}</b><strong>{number(balance.remaining)} <small>кредитов осталось</small></strong></div><progress max={balance.credits} value={Math.min(balance.used,balance.credits)}/><p>{balance.active?'Действует до':'Период закончился'} {new Date(balance.expires*1000).toLocaleString('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}. {balance.daily_remaining!==null&&`Сегодня доступно ${number(balance.daily_remaining)} кр. Дневной запас обновляется в 03:00 МСК.`}</p>{balance.pending>0&&<p>Есть резерв на выполняемые или прерванные запросы. При неизвестном расходе резерв сохраняется до сверки — support@rant.ae.</p>}</div>}<div className="cloud-plan-grid">{balance?.plans.map(p=><article key={p.id} className={p.id==='plus'?'featured':''}><h3>{p.name}</h3><strong>{number(p.price)} ₽<small> / 30 дней</small></strong><p>{number(p.credits)} кредитов</p><ul><li>Все модели GPT и Claude из каталога</li><li>История чатов и вложения</li><li>Работа с файлами и контекстом</li></ul><button disabled={!balance.payments_enabled||busy||!accept||(balance.active&&balance.plan!=='trial')} onClick={()=>void buy(p.id)}>{balance.payments_enabled?'Выбрать тариф':'Оплата скоро'}</button></article>)}</div>{balance?.payments_enabled&&<label className="cloud-terms"><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/>Принимаю <a href="/terms" target="_blank" rel="noreferrer">условия покупки</a>. Оплата однократная, без автопродления.</label>}<p className="cloud-fineprint">1 кредит = 1 ₽ расхода моделей по тарифам каталога. Количество сообщений зависит от модели, длины чата и ответа. Кредиты действуют в пределах периода, не переносятся и не выводятся в деньги. После пробного периода списаний нет. Обновление запаса — при оплате нового периода. Управление ПК из облака доступно через экспериментальный Rant Connect.</p>{error&&<p role="alert" className="cloud-error">{error}</p>}</DialogContent></Dialog></>;
}
