'use client';
import { t, useLanguage } from '@/lib/i18n';
import { isLocalEndpoint } from '@/lib/model-connection';
import {useState,useEffect} from 'react';
import {Cpu,Globe,Check,Plus,Settings2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import ContextSettings from '@/components/context-settings';
import {useAccount} from '@/components/account-gate';
export type Profile={id:string;name:string;kind:string;model:string;base_url:string;has_key?:boolean;auto_context?:boolean;context_tokens?:number};
type Api=<T>(route:string,data?:unknown)=>Promise<T>;
const blank:Profile={id:'',name:'',kind:'openai',model:'',base_url:'http://127.0.0.1:1234/v1'};
export default function ModelSettings({open,onClose,profiles,selected,onSelect,api,refresh,disabled,localStatus,localReason}:{open:boolean;onClose:()=>void;profiles:Profile[];selected:string;onSelect:(id:string)=>void;api:Api;refresh:()=>Promise<unknown>;disabled:boolean;localStatus?:string;localReason?:string}){
 useLanguage();
 const {cloud}=useAccount();
 const [draft,setDraft]=useState<Profile>(blank),[key,setKey]=useState(''),[provider,setProvider]=useState('local'),[models,setModels]=useState<string[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[adding,setAdding]=useState(false);
 useEffect(()=>{if(open){const current=profiles.find(p=>p.id===selected);if(current&&current.kind!=='local')edit(current);else{if(cloud)preset('timeweb');else setDraft(blank);setKey('');setAdding(cloud);setNotice('');setError('')}}},[open]);
 const localUnavailable=localStatus==='unavailable'||localStatus==='error';
 const localLabel=localStatus==='ready'?t("В памяти · готова к следующей задаче"):localStatus==='loading'?t("Загружается на этом Mac"):localStatus==='unavailable'?t("Требуется настройка"):localStatus==='error'?t("Не удалось загрузить"):t("Установлена · загрузится при первом сообщении");
 const localChosen=!adding&&profiles.find(p=>p.id===selected)?.kind==='local';
 async function safe(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:t("Ошибка подключения"))}finally{setBusy(false)}}
 function edit(p:Profile){setAdding(false);setDraft({...p,kind:p.base_url.includes('api.timeweb.ai')&&p.kind==='anthropic'?'openai':p.kind});setKey('');setModels([]);setError('');setNotice('');setProvider(p.base_url.includes('api.openai.com')?'openai':p.base_url.includes('api.anthropic.com')?'anthropic':p.base_url.includes('api.timeweb.ai')?'timeweb':p.base_url.includes(':11434')?'ollama':p.base_url.includes(':1234')?'lmstudio':/^http:\/\/(127\.0\.0\.1|localhost)/.test(p.base_url)?'local':'other')}
 function preset(value:string){setAdding(true);setProvider(value);setModels([]);setKey('');setDraft({...blank,kind:value==='openai'?'responses':value==='anthropic'?'anthropic':'openai',auto_context:!['ollama','lmstudio','local'].includes(value),context_tokens:8192,base_url:value==='openai'?'https://api.openai.com/v1':value==='anthropic'?'https://api.anthropic.com/v1':value==='timeweb'?'https://api.timeweb.ai/v1':value==='ollama'?'http://127.0.0.1:11434/v1':value==='lmstudio'||value==='local'?(cloud?'https://':'http://127.0.0.1:1234/v1'):''})}
 async function save(test=false){const p=await api<Profile>('profile',{...draft,name:draft.name.trim()||draft.model,key});setDraft(p);setKey('');onSelect(p.id);await refresh();if(test){const result=await api<{message:string}>('probe',{id:p.id});setNotice(result.message)}else setNotice(t("Подключение сохранено")+(p.has_key?t(" вместе с API-ключом"):'')+t(". Выбрана модель ")+p.model)}
 return <Dialog open={open} onOpenChange={v=>{if(!v){setKey('');onClose()}}}><DialogContent className="settings-dialog model-dialog"><DialogHeader><DialogTitle>{t("Модель и подключение")}</DialogTitle><DialogDescription>{t("Нажми на модель — её настройки появятся сразу. Ключ сохраняется после перезапуска.")}</DialogDescription></DialogHeader>
 <div className="model-list">{profiles.map(p=><div key={p.id} className={'model-card '+(selected===p.id?'chosen':'')}><button disabled={disabled} onClick={()=>{onSelect(p.id);if(p.kind!=='local')edit(p);else{setAdding(false);setDraft(blank);setKey('');setError('');setNotice(localUnavailable?'':t("Выбрана локальная Qwen. API-ключ не нужен."))}}}>{p.kind==='local'?<Cpu size={19}/>:<Globe size={19}/>}<span><b>{p.model}</b><small>{p.kind==='local'?localLabel:p.base_url.includes('api.timeweb.ai')?'Timeweb AI':p.name||p.base_url}</small></span>{selected===p.id&&<Check size={16}/>}</button></div>)}</div>
 {localStatus==='ready'&&<Button variant="outline" size="sm" disabled={disabled||busy} onClick={()=>safe(async()=>{await api('model-unload',{});await refresh();setNotice(t("Память освобождена. Следующая локальная задача загрузит модель снова."))})}>{t("Выгрузить Qwen из памяти")}</Button>}
 <p className="form-help"><a href="/help.html" target="_blank" rel="noreferrer">{t("Установка Qwen, Ollama, LM Studio и API →")}</a></p><div className="connection-heading"><h3>{localChosen?t("Локальная модель"):draft.id?t("Настройки ")+draft.model:t("Новое подключение")}</h3><button className="text-button" onClick={()=>preset('other')}><Plus size={13}/>{t("Добавить модель")}</button></div>
 {localChosen?<><p className={localUnavailable?"message error":"form-help"} role={localUnavailable?"alert":undefined}>{localUnavailable?((localReason?t(localReason):'')||t("Локальная Qwen пока недоступна. Проверь установку модели.")):localStatus==='loading'?t("Qwen загружается в память. Первый ответ может занять немного больше времени."):localStatus==='ready'?t("Qwen загружена и готова отвечать на этом Mac. Закрой это окно и напиши сообщение."):t("Qwen установлена и загрузится при первом сообщении. Она работает на этом Mac, API-ключ не нужен.")}</p>{notice&&<p role="status" className="message notice">{t(notice)}</p>}</>:<>
 <div className="provider-options">{[['openai','OpenAI · GPT'],['anthropic','Anthropic · Claude'],['timeweb','Timeweb AI'],['ollama','Ollama'],['lmstudio','LM Studio'],['local',t("Свой сервер")],['other',t("Другой сервис")]].map(([id,label])=><button key={id} className={provider===id?'selected':''} onClick={()=>preset(id)}>{label}</button>)}</div>
 {['ollama','lmstudio'].includes(provider)&&<p className="form-help">{provider==='ollama'?t("Запусти Ollama и скачай модель командой ollama pull qwen3:4b. Затем получи список моделей ниже."):t("Загрузи модель в LM Studio, открой Developer и нажми Start Server. Затем получи список моделей ниже.")} <a href="/help.html" target="_blank" rel="noreferrer">{t("Подробная установка")}</a></p>}
 <label>{t("Адрес сервера")}<input value={draft.base_url} placeholder="https://…/v1" onChange={e=>{const url=e.target.value;setDraft({...draft,base_url:url,kind:url.includes('api.timeweb.ai')?'openai':draft.kind});setModels([])}}/></label>
 <label>{isLocalEndpoint(draft.base_url)?t("API-ключ (необязательно)"):t("API-ключ")}<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={draft.has_key?t("Ключ сохранён · оставь пустым, чтобы не менять"):isLocalEndpoint(draft.base_url)?t("Не нужен для обычного локального сервера"):t("Ключ из кабинета провайдера")}/></label>
 {draft.has_key&&<button className="text-button" disabled={busy||disabled} onClick={()=>safe(async()=>{const p=await api<Profile>('profile',{...draft,clear_key:true});setDraft(p);setKey('');await refresh();setNotice(t("Сохранённый ключ удалён. Подключение осталось в списке."))})}>{t("Удалить сохранённый ключ")}</button>}
 <div className="model-picker-heading"><label htmlFor="model-id">{t("Модель")}</label><button className="text-button" disabled={busy||disabled||!draft.base_url} onClick={()=>safe(async()=>{const result=await api<{models:string[]}>('models',{draft:{...draft,key}});setModels(result.models);setNotice(result.models.length?t("Выбери точное название из списка ниже."):t("Сервис вернул пустой список. Можно указать модель вручную."))})}>{t("Получить список с сервера")}</button></div>
 {models.length>0&&<div className="catalog"><input aria-label={t("Поиск модели")} placeholder={t("Найти в списке…")} value={query} onChange={e=>setQuery(e.target.value)}/><div>{models.filter(m=>m.toLowerCase().includes(query.toLowerCase())).slice(0,80).map(m=><button className={m===draft.model?'selected':''} key={m} onClick={()=>setDraft({...draft,model:m})}>{m}{m===draft.model&&<Check size={12}/>}</button>)}</div></div>}
 <input id="model-id" aria-label={t("Точное название модели")} value={draft.model} onChange={e=>setDraft({...draft,model:e.target.value})} placeholder={provider==='timeweb'?t("Например: openai/gpt-4o"):t("Точный идентификатор с сервера")}/>
 <details className="connection-advanced"><summary>{t("Дополнительные настройки")}</summary><label>{t("Название подключения")}<input value={draft.name} placeholder={t("Необязательно")} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{t("Формат запросов")}</label><Select value={draft.kind} onValueChange={v=>setDraft({...draft,kind:String(v)})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="openai">Chat Completions</SelectItem><SelectItem value="responses">{t("Responses — новые GPT и инструменты")}</SelectItem>{provider!=='timeweb'&&<SelectItem value="anthropic">Anthropic Messages</SelectItem>}</SelectContent></Select><p>{t("Провайдер задаёт формат по умолчанию. Для нового GPT с инструментами используй Responses; для Claude напрямую — Anthropic Messages.")}</p></details>
 <ContextSettings value={draft} disabled={busy||disabled} onChange={settings=>setDraft({...draft,...settings})}/>
 {error&&<div className="message error" role="alert">{t(error)}</div>}{notice&&<div className="message notice" role="status">{t(notice)}</div>}
 <div className="form-actions"><Button disabled={busy||disabled||!draft.model.trim()||!draft.base_url.trim()} onClick={()=>safe(()=>save(true))}>{busy?t("Подключаю…"):t("Сохранить и проверить")}</Button><Button variant="outline" disabled={busy||disabled||!draft.model.trim()||!draft.base_url.trim()} onClick={()=>safe(()=>save())}>{t("Сохранить")}</Button></div>
 <p className="form-help">{t("Проверка отправит короткий запрос именно этой модели. ")}{cloud?t("Ключ хранится в твоём аккаунте на сервере и доступен только твоим чатам."):t("Ключ сохраняется на этом компьютере и автоматически восстанавливается после перезапуска.")}{t(" Для работы агента модель должна поддерживать вызов инструментов.")}</p>
 </>}<div className="model-done"><Button variant="outline" disabled={busy} onClick={()=>{setKey('');onClose()}}>{t("Готово")}</Button></div></DialogContent></Dialog>
}
